import streamlit as st
import pandas as pd
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer

st.set_page_config(page_title="Financial Dashboard", layout="wide")

st.title("📊 Financial Topic Modeling Dashboard")

# Load data
df = pd.read_csv("title,description,text,clean_text,topic,topic_name,sentiment
"Stock Market Today: Oil Soars to $115 a Barrel, Dow Futures Inch Lower — Live Updates - WSJ",,"Stock Market Today: Oil Soars to $115 a Barrel, Dow Futures Inch Lower — Live Updates - WSJ ",stock market today oil soars barrel dow futures inch lower live updates wsj,0,Stock Market,0.13636363636363635
Eli Lilly’s next-generation obesity drug retatrutide clears first late-stage diabetes trial - CNBC,"Lilly is betting big on retatrutide as the next pillar of its obesity portfolio after its weight loss injection Zepbound and its upcoming pill, orforglipron.","Eli Lilly’s next-generation obesity drug retatrutide clears first late-stage diabetes trial - CNBC Lilly is betting big on retatrutide as the next pillar of its obesity portfolio after its weight loss injection Zepbound and its upcoming pill, orforglipron.",eli lillys nextgeneration obesity drug retatrutide clears latestage diabetes trial cnbc lilly betting big retatrutide pillar obesity portfolio weight loss injection zepbound upcoming pill orforglipron,3,,0.08333333333333333
‘Epic Fury’ has already canceled out Big Beautiful Bill’s tax refunds — even if the Iran war ended today - MarketWatch,,‘Epic Fury’ has already canceled out Big Beautiful Bill’s tax refunds — even if the Iran war ended today - MarketWatch ,epic fury canceled big beautiful bills tax refunds iran war ended today marketwatch,0,Stock Market,0.31666666666666665
Scoreboard on every street: Gas heads for $4 per gallon due to Iran war - Axios,The most visible barometer for many Americans of how it's going in Iran may well be the price posted at the gas station down the street.,Scoreboard on every street: Gas heads for $4 per gallon due to Iran war - Axios The most visible barometer for many Americans of how it's going in Iran may well be the price posted at the gas station down the street.,scoreboard street gas heads gallon iran war axios visible barometer americans going iran price posted gas station street,0,Stock Market,0.1798611111111111
"This tax season, there's a new deduction for interest on car loans - NPR",Taxpayers who purchased a new vehicle in 2025 may qualify for a new deduction on their taxes — even if they're not itemizing. But not everyone is eligible.,"This tax season, there's a new deduction for interest on car loans - NPR Taxpayers who purchased a new vehicle in 2025 may qualify for a new deduction on their taxes — even if they're not itemizing. But not everyone is eligible.",tax season theres new deduction car loans npr taxpayers purchased new vehicle qualify new deduction taxes theyre itemizing eligible,2,Mergers & Acquisitions,0.13636363636363635
It's called 'private credit' — and it could lead to big trouble on Wall Street - NPR,The risky lending business has been booming — but now its problems are becoming increasingly visible on Wall Street and beyond.,It's called 'private credit' — and it could lead to big trouble on Wall Street - NPR The risky lending business has been booming — but now its problems are becoming increasingly visible on Wall Street and beyond.,called private credit lead big trouble wall street npr risky lending business booming problems increasingly visible wall street,1,Inflation,0.0625
‘What is he doing?’: New threats emerge for Trump’s economy as war drags on - Politico,Recent reports suggest the president may have only a thin buffer to rely on if a prolonged conflict starts to weaken growth and spur inflation.,‘What is he doing?’: New threats emerge for Trump’s economy as war drags on - Politico Recent reports suggest the president may have only a thin buffer to rely on if a prolonged conflict starts to weaken growth and spur inflation.,doing new threats emerge trumps economy war drags politico recent reports suggest president buffer rely prolonged conflict starts weaken growth spur inflation,0,Stock Market,-0.06590909090909092
Oil Rises After Attacks on Middle East Energy Sites; Asian Stocks Fall - WSJ,U.S. stock futures edged lower,Oil Rises After Attacks on Middle East Energy Sites; Asian Stocks Fall - WSJ U.S. stock futures edged lower,oil rises attacks middle east energy sites asian stocks fall wsj stock futures edged lower,0,Stock Market,0.0
"Live updates: Interest rates steady, Federal Reserve forecasts one rate cut in 2026 - Yahoo Finance",The Federal Reserve kept interest rates unchanged at the end of its two-day policy meeting on Wednesday.,"Live updates: Interest rates steady, Federal Reserve forecasts one rate cut in 2026 - Yahoo Finance The Federal Reserve kept interest rates unchanged at the end of its two-day policy meeting on Wednesday.",live updates rates steady federal reserve forecasts rate cut yahoo finance federal reserve kept rates unchanged end twoday policy meeting wednesday,0,Stock Market,0.1515151515151515
"Trump tried to push Powell out, but now he may be stuck with him - The Washington Post",Powell says he would remain as Fed chief and stay on the board — as Trump’s efforts to reshape the Fed run into legal and political roadblocks.,"Trump tried to push Powell out, but now he may be stuck with him - The Washington Post Powell says he would remain as Fed chief and stay on the board — as Trump’s efforts to reshape the Fed run into legal and political roadblocks.",trump tried push powell stuck washington post powell says remain fed chief stay board trumps efforts reshape fed run legal political roadblocks,0,Stock Market,0.1
Sound Transit's Budget-Balancing Ideas All Stop Short of Delivering Rail to Ballard - The Urbanist,"At a board retreat Wednesday, Sound Transit weighed three cost-cutting approaches that all included deferring light rail stations in Ballard and Interbay to a later date when funding allows. Seattle Councilmember Dan Strauss pushed back against that approach.","Sound Transit's Budget-Balancing Ideas All Stop Short of Delivering Rail to Ballard - The Urbanist At a board retreat Wednesday, Sound Transit weighed three cost-cutting approaches that all included deferring light rail stations in Ballard and Interbay to a later date when funding allows. Seattle Councilmember Dan Strauss pushed back against that approach.",sound transits budgetbalancing ideas stop short delivering rail ballard urbanist board retreat wednesday sound transit weighed costcutting approaches included deferring light rail stations ballard interbay later date funding allows seattle councilmember dan strauss pushed approach,4,,0.20000000000000004
Amazon Alexa's UK personality to change with Echo AI update - BBC,"There has been criticism the Echo has stagnated, while other AI chatbots have become much easier to communicate with.","Amazon Alexa's UK personality to change with Echo AI update - BBC There has been criticism the Echo has stagnated, while other AI chatbots have become much easier to communicate with.",amazon alexas uk personality change echo ai update bbc criticism echo stagnated ai chatbots easier communicate,2,Mergers & Acquisitions,0.037500000000000006
HDFC Bank shares fall 5% as part-time chair of India’s largest private bank resigns over 'ethics' - CNBC,"Interim part‑time chairman, Keki Mistry, said that Atanu Chakraborty, had not provided the board with any evidence or details of the alleged unethical practices.","HDFC Bank shares fall 5% as part-time chair of India’s largest private bank resigns over 'ethics' - CNBC Interim part‑time chairman, Keki Mistry, said that Atanu Chakraborty, had not provided the board with any evidence or details of the alleged unethical practices.",hdfc bank shares fall parttime chair indias largest private bank resigns ethics cnbc interim parttime chairman keki mistry said atanu chakraborty provided board evidence details alleged unethical practices,1,Inflation,-0.05
"Bank of Japan keeps rates steady as expected, warns Iran war may push up inflation - CNBC","The Bank of Japan kept its rates steady at 0.75% as expected, but noted that inflation risks now are tilted to the upside due to the Iran war.","Bank of Japan keeps rates steady as expected, warns Iran war may push up inflation - CNBC The Bank of Japan kept its rates steady at 0.75% as expected, but noted that inflation risks now are tilted to the upside due to the Iran war.",bank japan keeps rates steady expected warns iran war push inflation cnbc bank japan kept rates steady expected noted inflation risks tilted upside iran war,0,Stock Market,0.0016666666666666607
Tillis: Negotiators ‘very close’ to stablecoin yield deal to unlock crypto bill - Politico,Republican senators said Wednesday they hope to revive the bill next month.,Tillis: Negotiators ‘very close’ to stablecoin yield deal to unlock crypto bill - Politico Republican senators said Wednesday they hope to revive the bill next month.,tillis negotiators close stablecoin yield deal unlock crypto politico republican senators said wednesday hope revive month,0,Stock Market,0.1
Japan rebels over $6bn fee for SoftBank under US trade deal - Financial Times,Dispute about power station payment shows Tokyo’s unease with governance of $550bn in investments,Japan rebels over $6bn fee for SoftBank under US trade deal - Financial Times Dispute about power station payment shows Tokyo’s unease with governance of $550bn in investments,japan rebels bn fee softbank trade deal financial times dispute power station payment shows tokyos unease governance bn investments,1,Inflation,0.0
US Tells Companies to Secure Microsoft System After Stryker Hack - Bloomberg.com,"The US government is warning businesses to secure their corporate accounts within a popular Microsoft Corp. management tool, following a cyberattack on Stryker Corp. last week.","US Tells Companies to Secure Microsoft System After Stryker Hack - Bloomberg.com The US government is warning businesses to secure their corporate accounts within a popular Microsoft Corp. management tool, following a cyberattack on Stryker Corp. last week.",tells companies secure microsoft stryker hack bloombergcom government warning businesses secure corporate accounts popular microsoft corp management tool following cyberattack stryker corp week,-1,,0.2333333333333333
"How the Fed meeting will impact mortgage rates, housing market - thestreet.com","Mortgage rates may still shift, even when the fed funds rate holds steady.","How the Fed meeting will impact mortgage rates, housing market - thestreet.com Mortgage rates may still shift, even when the fed funds rate holds steady.",fed meeting impact mortgage rates housing market thestreetcom mortgage rates shift fed funds rate holds steady,0,Stock Market,0.16666666666666666
USPS says it may not deliver mail in a year - WSB-TV,"The United States Postal Service is warning it could soon face a financial breaking point, with leaders saying the agency may not be able to continue delivering mail or paying workers within the next year if changes aren’t made.","USPS says it may not deliver mail in a year - WSB-TV The United States Postal Service is warning it could soon face a financial breaking point, with leaders saying the agency may not be able to continue delivering mail or paying workers within the next year if changes aren’t made.",usps says deliver mail year wsbtv united states postal service warning soon face financial breaking point leaders saying agency able continue delivering mail paying workers year changes arent,4,,0.16666666666666666
In vivo site-specific engineering to reprogram T cells - Nature,Stable and cell-specific transgene expression can be achieved through in vivo site-specific integration of large DNA payloads using a&nbsp;two-vector system of enveloped delivery vehicles and adeno-associated viruses.,In vivo site-specific engineering to reprogram T cells - Nature Stable and cell-specific transgene expression can be achieved through in vivo site-specific integration of large DNA payloads using a&nbsp;two-vector system of enveloped delivery vehicles and adeno-associated viruses.,vivo sitespecific engineering reprogram t cells nature stable cellspecific transgene expression achieved vivo sitespecific integration large dna payloads using anbsptwovector enveloped delivery vehicles adenoassociated viruses,3,,0.21428571428571427
Powell Delivers Damning Report on Trump’s Flailing Economy - The Daily Beast,The Federal Reserve chair refused to bow down to Trump’s demands to cut interest rates.,Powell Delivers Damning Report on Trump’s Flailing Economy - The Daily Beast The Federal Reserve chair refused to bow down to Trump’s demands to cut interest rates.,powell delivers damning report trumps flailing economy daily beast federal reserve chair refused bow trumps demands cut rates,0,Stock Market,-0.07777777777777778
Disney CEO Succession Drama-Free For First Time In Recent History - Deadline,"A new Disney CEO is a momentous thing, and what's even more notable about the transition from Bob Iger to Josh D'Amaro is that it's been drama-free.","Disney CEO Succession Drama-Free For First Time In Recent History - Deadline A new Disney CEO is a momentous thing, and what's even more notable about the transition from Bob Iger to Josh D'Amaro is that it's been drama-free.",disney ceo succession dramafree time recent history deadline new disney ceo momentous thing whats notable transition bob iger josh damaro dramafree,1,Inflation,0.2772727272727272
Why Global Energy Shock Could Leave China Stronger Than Ever - Crude Oil Prices Today | OilPrice.com,China is positioned to become a major economic winner from the Middle East energy crisis due to its massive strategic oil stockpiles and long-term investment in a resilient 'supergrid' and renewable energy buildout.,Why Global Energy Shock Could Leave China Stronger Than Ever - Crude Oil Prices Today | OilPrice.com China is positioned to become a major economic winner from the Middle East energy crisis due to its massive strategic oil stockpiles and long-term investment in a resilient 'supergrid' and renewable energy buildout.,global energy shock leave china stronger crude oil prices today oilpricecom china positioned major economic winner middle east energy crisis massive strategic oil stockpiles longterm investment resilient supergrid renewable energy buildout,0,Stock Market,-0.08035714285714286
Amazon doesn’t want the blame for the Post Office going under - The Verge,"Amazon says the USPS “walked away” from negotiations on a new contract in December, claiming it has received “no response” on a bid for last-mile deliveries in February.","Amazon doesn’t want the blame for the Post Office going under - The Verge Amazon says the USPS “walked away” from negotiations on a new contract in December, claiming it has received “no response” on a bid for last-mile deliveries in February.",amazon doesnt want blame post office going verge amazon says usps walked away negotiations new contract december claiming received response bid lastmile deliveries february,4,,0.13636363636363635
Gas price spike spurs a political blame game in California - NPR,"California's gas prices have long been high, and spikes due to the war with Iran have sparked debate over who's to blame. Some Democrats say Gov. Gavin Newsom could do more to ease prices.","Gas price spike spurs a political blame game in California - NPR California's gas prices have long been high, and spikes due to the war with Iran have sparked debate over who's to blame. Some Democrats say Gov. Gavin Newsom could do more to ease prices.",gas price spike spurs political blame game california npr californias gas prices long high spikes war iran sparked debate whos blame democrats say gov gavin newsom ease prices,0,Stock Market,0.01416666666666666
"Gold Holds Steady Near $5,000 as Traders Weigh Fed Rate-Cut Path - Bloomberg.com","Gold declined for a sixth day, its longest losing streak since late 2024, as Federal Reserve Chair Jerome Powell said higher energy prices will push up overall inflation.","Gold Holds Steady Near $5,000 as Traders Weigh Fed Rate-Cut Path - Bloomberg.com Gold declined for a sixth day, its longest losing streak since late 2024, as Federal Reserve Chair Jerome Powell said higher energy prices will push up overall inflation.",gold holds steady near traders weigh fed ratecut path bloombergcom gold declined sixth day longest losing streak late federal reserve chair jerome powell said higher energy prices push overall inflation,0,Stock Market,0.043333333333333335
Investors Should Position for a Longer Iran War. What to Do Now. - Barron's,The risk is that the war lasts longer than expected and the shipping industry takes even longer to recover. The recent weakness in financial markets could be an amuse-bouche before a bearish feast.,Investors Should Position for a Longer Iran War. What to Do Now. - Barron's The risk is that the war lasts longer than expected and the shipping industry takes even longer to recover. The recent weakness in financial markets could be an amuse-bouche before a bearish feast.,investors position longer iran war barrons risk war lasts longer expected shipping industry takes longer recover recent weakness financial markets amusebouche bearish feast,0,Stock Market,-0.03333333333333333
Rocket Lab Stock: Launch Toward A Likely 27% Return With This Bullish Trade - Investor's Business Daily,Rocket Lab stock is a candidate for a bullish options trade. This strategy could bring in a potential 27% return in four weeks.,Rocket Lab Stock: Launch Toward A Likely 27% Return With This Bullish Trade - Investor's Business Daily Rocket Lab stock is a candidate for a bullish options trade. This strategy could bring in a potential 27% return in four weeks.,rocket lab stock launch likely return bullish trade investors business daily rocket lab stock candidate bullish options trade strategy bring potential return weeks,0,Stock Market,0.0
Micron Earnings Face High Expectations as Its Stock Keeps Rising - Yahoo Finance,"Micron shares have soared 63% to start the year, among the best performers in the S&P 500 Index, after jumping 239% in 2025.  The biggest US maker of memory ...","Micron Earnings Face High Expectations as Its Stock Keeps Rising - Yahoo Finance Micron shares have soared 63% to start the year, among the best performers in the S&P 500 Index, after jumping 239% in 2025.  The biggest US maker of memory ...",micron earnings face high expectations stock keeps rising yahoo finance micron shares soared start year best performers sp index jumping biggest maker memory,-1,,0.58
Elon Musk clarifies viral Tesla Cybertruck accident with driver logs - Teslarati,Musk has come out to say that the driver logs have already shown that the driver,Elon Musk clarifies viral Tesla Cybertruck accident with driver logs - Teslarati Musk has come out to say that the driver logs have already shown that the driver,elon musk clarifies viral tesla cybertruck accident driver logs teslarati musk come say driver logs shown driver,2,Mergers & Acquisitions,0.0
Fannie Mae and Freddie Mac Remove Certain Homeowners Insurance Requirements That Will Reduce Costs - FHFA (.gov),"American homebuyers are about to get a break. New rules for Fannie Mae and Freddie Mac mortgages will help to lower home insurance bills for millions of families, especially in rural areas and condo buildings. The changes fix expensive, stupid Biden-era requi…","Fannie Mae and Freddie Mac Remove Certain Homeowners Insurance Requirements That Will Reduce Costs - FHFA (.gov) American homebuyers are about to get a break. New rules for Fannie Mae and Freddie Mac mortgages will help to lower home insurance bills for millions of families, especially in rural areas and condo buildings. The changes fix expensive, stupid Biden-era requi…",fannie mae freddie mac remove certain homeowners insurance requirements reduce costs fhfa gov american homebuyers break new rules fannie mae freddie mac mortgages help lower home insurance bills millions families especially rural areas condo buildings changes fix expensive stupid bidenera requi,-1,,-0.1582251082251082
TSA PreCheck Touchless ID can save you time as airport lines get longer. Here's how to sign up. - CBS News,"Travelers hoping to bypass some of the increasingly long wait times at U.S. airports can enroll in the TSA PreCheck Touchless ID program, which is now operating at 65 locations.","TSA PreCheck Touchless ID can save you time as airport lines get longer. Here's how to sign up. - CBS News Travelers hoping to bypass some of the increasingly long wait times at U.S. airports can enroll in the TSA PreCheck Touchless ID program, which is now operating at 65 locations.",tsa precheck touchless id save time airport lines longer heres sign cbs news travelers hoping bypass increasingly long wait times airports enroll tsa precheck touchless id program operating locations,4,,-0.05
"J&J, Protagonist's 'game-changer' once-daily psoriasis pill Icotyde nabs FDA approval - Fierce Pharma",Johnson & Johnson and Protagonist Therapeutics are countering the swarm of injectable biologics that have long dominated the lucrative psoriasis market with a new approval for a much-anticipate | The once-daily pill stands to shake up the injectable-filled ps…,"J&J, Protagonist's 'game-changer' once-daily psoriasis pill Icotyde nabs FDA approval - Fierce Pharma Johnson & Johnson and Protagonist Therapeutics are countering the swarm of injectable biologics that have long dominated the lucrative psoriasis market with a new approval for a much-anticipate | The once-daily pill stands to shake up the injectable-filled ps…",jj protagonists gamechanger oncedaily psoriasis pill icotyde nabs fda approval fierce pharma johnson johnson protagonist therapeutics countering swarm injectable biologics long dominated lucrative psoriasis market new approval muchanticipate oncedaily pill stands shake injectablefilled ps,3,,0.043181818181818175
Trump's tariffs are causing harm to American manufacturers instead of benefiting them - PBS,The White House says the Republican president's policies will take time to make a difference.,Trump's tariffs are causing harm to American manufacturers instead of benefiting them - PBS The White House says the Republican president's policies will take time to make a difference.,trumps tariffs causing harm american manufacturers instead benefiting pbs white house says republican presidents policies time make difference,0,Stock Market,0.0
Washington opens Tesla’s direct EV sales loophole to Rivian and Lucid - Electrek,"Washington state legislators just voted overwhelmingly to allow Rivian and Lucid to sell electric vehicles directly to consumers, ending a...","Washington opens Tesla’s direct EV sales loophole to Rivian and Lucid - Electrek Washington state legislators just voted overwhelmingly to allow Rivian and Lucid to sell electric vehicles directly to consumers, ending a...",washington opens teslas direct ev sales loophole rivian lucid electrek washington state legislators just voted overwhelmingly allow rivian lucid sell electric vehicles directly consumers ending,2,Mergers & Acquisitions,0.2333333333333333
Bank of America resets Nvidia stock forecast after meeting with CFO - thestreet.com,Here’s what BofA says could happen to Nvidia shares next.,Bank of America resets Nvidia stock forecast after meeting with CFO - thestreet.com Here’s what BofA says could happen to Nvidia shares next.,bank america resets nvidia stock forecast meeting cfo thestreetcom heres bofa says happen nvidia shares,-1,,0.0
"US wholesale prices rose by a surprisingly hot 3.4% last month, the most in a year - AP News",U.S. wholesale prices came in hotter than expected in February. The Labor Department reported Wednesday that its producer price index — which measures inflation before it hits consumers — rose 0.7% from January and 3.4% from February 2025. The year-over-year …,"US wholesale prices rose by a surprisingly hot 3.4% last month, the most in a year - AP News U.S. wholesale prices came in hotter than expected in February. The Labor Department reported Wednesday that its producer price index — which measures inflation before it hits consumers — rose 0.7% from January and 3.4% from February 2025. The year-over-year …",wholesale prices rose surprisingly hot month year ap news wholesale prices came hotter expected february labor department reported wednesday producer price index measures inflation hits consumers rose january february yearoveryear,0,Stock Market,0.30833333333333335
BMW’s New i3 Sedan Targets Tesla Model 3 in a World of Electric SUVs - Gizmodo,"While its rivals keep rethinking their EV strategies, BMW has persisted.","BMW’s New i3 Sedan Targets Tesla Model 3 in a World of Electric SUVs - Gizmodo While its rivals keep rethinking their EV strategies, BMW has persisted.",bmws new sedan targets tesla model world electric suvs gizmodo rivals rethinking ev strategies bmw persisted,2,Mergers & Acquisitions,0.13636363636363635
NIH invests $150 million in human-based research to reduce use of animal models - National Institutes of Health (.gov),"New program will develop, validate and standardize research tools to develop more sophisticated and relevant models of disease.","NIH invests $150 million in human-based research to reduce use of animal models - National Institutes of Health (.gov) New program will develop, validate and standardize research tools to develop more sophisticated and relevant models of disease.",nih invests million humanbased research reduce use animal models national institutes health gov new programwill developvalidateand standardize research tools todevelop sophisticated relevant models disease,3,,0.38409090909090904
Lawsuit by South End landlord details fraud allegation against Croft School founder - and demand for at least $14 million in damages for failed lease deal - Universal Hub,The owners of the South End building where the Foodie's market was supposed to make way for a new branch of the Croft School yesterday sued the school and now suspended school Executive Director Scott Given over what they said was a completely fraudulent leas…,Lawsuit by South End landlord details fraud allegation against Croft School founder - and demand for at least $14 million in damages for failed lease deal - Universal Hub The owners of the South End building where the Foodie's market was supposed to make way for a new branch of the Croft School yesterday sued the school and now suspended school Executive Director Scott Given over what they said was a completely fraudulent leas…,lawsuit south end landlord details fraud allegation croft school founder demand million damages failed lease deal universal hub owners south end building foodies market supposed make way new branch croft school yesterday sued school suspended school executive director scott given said completely fraudulent leas,1,Inflation,-0.11272727272727275
"Rising Diesel Prices Should Concern All, Not Just Truckers - Newser",Spiking transport costs threaten to push core inflation even higher,"Rising Diesel Prices Should Concern All, Not Just Truckers - Newser Spiking transport costs threaten to push core inflation even higher",rising diesel prices concern just truckers newser spiking transport costs threaten push core inflation higher,0,Stock Market,0.25
What to know about Bill Gates’ nuclear science company planned for the former South Philadelphia refinery site - WHYY,"TerraPower Isotopes will manufacture a rare, radioactive isotope for use in developing cancer treatments.","What to know about Bill Gates’ nuclear science company planned for the former South Philadelphia refinery site - WHYY TerraPower Isotopes will manufacture a rare, radioactive isotope for use in developing cancer treatments.",know gates nuclear science company planned south philadelphia refinery site whyy terrapower isotopes manufacture rare radioactive isotope use developing cancer treatments,-1,,0.15
"Bitcoin news today: BTC price fails to penetrate $75,000 even after SEC, CFTC crypto guidance - CoinDesk","Bitcoin remains stuck near key resistance around $75,000, leaving the broader market in limbo.","Bitcoin news today: BTC price fails to penetrate $75,000 even after SEC, CFTC crypto guidance - CoinDesk Bitcoin remains stuck near key resistance around $75,000, leaving the broader market in limbo.",bitcoin news today btc price fails penetrate sec cftc crypto guidance coindesk bitcoin remains stuck near key resistance leaving broader market limbo,0,Stock Market,-0.125
BIG WINNER! Lucky lottery ticket sold in Ohio hits Mega Millions jackpot worth $60 million: See which store sold the winning ticket - WKYC,Wow! Somebody who bought their Mega Millions lottery ticket in Ohio is waking up as the world's newest multimillionaire!,BIG WINNER! Lucky lottery ticket sold in Ohio hits Mega Millions jackpot worth $60 million: See which store sold the winning ticket - WKYC Wow! Somebody who bought their Mega Millions lottery ticket in Ohio is waking up as the world's newest multimillionaire!,big winner lucky lottery ticket sold ohio hits mega millions jackpot worth million store sold winning ticket wkyc wow somebody bought mega millions lottery ticket ohio waking worlds newest multimillionaire,1,Inflation,0.2579166666666667
Nvidia Gets H200 Green Light in China. What’s Next for NVDA Stock? - TipRanks,"Nvidia ($NVDA), the AI chip leader, may be getting a second shot at one of its biggest markets. After months of delays, China has reportedly approved sales of Nvidia’s H200","Nvidia Gets H200 Green Light in China. What’s Next for NVDA Stock? - TipRanks Nvidia ($NVDA), the AI chip leader, may be getting a second shot at one of its biggest markets. After months of delays, China has reportedly approved sales of Nvidia’s H200",nvidia gets h green light china whats nvda stock tipranks nvidia nvda ai chip leader getting second shot biggest markets months delays china reportedly approved sales nvidias h,-1,,0.05
BP Whiting refinery initiates lockout after failed contract negotiations with USW members - CBS News,"The decision comes after Tuesday's meeting, where the refinery said the United Steelworkers Union, which represents 900 workers at the refinery, rejected the company's revised offer.","BP Whiting refinery initiates lockout after failed contract negotiations with USW members - CBS News The decision comes after Tuesday's meeting, where the refinery said the United Steelworkers Union, which represents 900 workers at the refinery, rejected the company's revised offer.",bp whiting refinery initiates lockout failed contract negotiations usw members cbs news decision comes tuesdays meeting refinery said united steelworkers union represents workers refinery rejected companys revised offer,-1,,-0.5
Bank of America settles lawsuit brought on behalf of Jeffrey Epstein victims - PBS,Bank of America has tentatively settled a lawsuit claiming it ignored suspicious financial transactions involving Jeffrey Epstein while he was sexually abusing hundreds of girls and women.,Bank of America settles lawsuit brought on behalf of Jeffrey Epstein victims - PBS Bank of America has tentatively settled a lawsuit claiming it ignored suspicious financial transactions involving Jeffrey Epstein while he was sexually abusing hundreds of girls and women.,bank america settles lawsuit brought behalf jeffrey epstein victims pbs bank america tentatively settled lawsuit claiming ignored suspicious financial transactions involving jeffrey epstein sexually abusing hundreds girls women,1,Inflation,0.25")

docs = df["clean_text"].tolist()

# Train model LIVE (important)
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

topic_model = BERTopic(
    embedding_model=embedding_model,
    min_topic_size=3
)

topics, probs = topic_model.fit_transform(docs)

# Show topics
st.subheader("📌 Topics")
st.dataframe(topic_model.get_topic_info())

# Visualization
st.subheader("📈 Visualization")
try:
    st.plotly_chart(topic_model.visualize_topics(), use_container_width=True)
except:
    st.plotly_chart(topic_model.visualize_barchart(), use_container_width=True)

# Distribution
st.subheader("📊 Topic Distribution")
df["topic"] = topics
st.bar_chart(df["topic"].value_counts())

# Data preview
st.subheader("📰 Data")
st.dataframe(df.head(20))
